from typing import List, Dict, Any, Tuple

def read_daily_bars(
    filepath: str,
    price_coeff: float = 0.01,
    vol_coeff: float = 0.01,
) -> List[Dict[str, Any]]: ...

def read_minute_bars(filepath: str) -> List[Dict[str, Any]]: ...

def ping_servers(servers: List[Tuple[str, int]]) -> List[Tuple[str, int, int]]: ...

class TdxClient:
    def __init__(self) -> None: ...
    def connect(self, ip: str, port: int) -> bool: ...
    def disconnect(self) -> None: ...
    def get_security_bars(self, category: int, market: int, code: str, start: int, count: int) -> List[Dict[str, Any]]: ...
    def get_report_file(self, filename: str, offset: int) -> Tuple[int, bytes]: ...
