from typing import Any, Dict, List, Tuple

def read_daily_bars(
    filepath: str,
    price_coeff: float = 0.01,
    vol_coeff: float = 0.01,
) -> List[Dict[str, Any]]: ...

def read_minute_bars(filepath: str) -> List[Dict[str, Any]]: ...

def ping_servers(servers: List[Tuple[str, int]]) -> List[Tuple[str, int, int]]: ...

class TdxClient:
    def __init__(self) -> None: ...
    def connect(self, ip: str, port: int) -> bool: ...
    def disconnect(self) -> None: ...
    def get_security_bars(self, category: int, market: int, code: str, start: int, count: int) -> List[Dict[str, Any]]: ...
    def get_report_file(self, filename: str, offset: int) -> Tuple[int, bytes]: ...
    def get_xdxr_info(self, market: int, code: str) -> List[Dict[str, Any]]: ...
    def get_transaction_data(self, market: int, code: str, start: int, count: int) -> List[Dict[str, Any]]: ...
    def get_security_quotes(self, stock_list: List[Tuple[int, str]]) -> List[Dict[str, Any]]: ...
    def get_company_info_category(self, market: int, code: str) -> List[Dict[str, Any]]: ...
    def get_company_info_content(self, market: int, code: str, filename: str, start: int, length: int) -> str: ...
